---
name: instagcn
version: 1
handle:
- expire: if(path ~ "(.*)\.(js|css|jpg|png|gif|ico)") time 31536000
- compress: if(out_header["Content-Length"] >= 1240) compress
- hostaccess: if(path ~ "/cron/") allow "10.0.0.0/8"

handlers:
- url: /static/
  gzip: on

- url: /
  gzip: on

cron:
- description: init popular
  url: /cron/popular
  schedule: every 3 mins
  timezone: Beijing
